ingress:
  enabled: false
  host: construct-x.borrmann.dev
  tlsSecret: construct-x-tls

clusterIssuer:
  enabled: true
  name: letsencrypt-prod
  email: dennis@borrmann.dev

edc:
  enabled: true
  seedTestdata: true
  backendUrl: http://{{ .Release.Name }}-dataprovider-x-submodelserver:8080
  registryUrl: http://{{ .Release.Name }}-dataprovider-x-dtr:8080/api/v3
  controlplanePublicUrl: http://{{ .Release.Name }}-dataprovider-x-edc-controlplane:8084
  controlplaneManagementUrl: http://{{ .Release.Name }}-dataprovider-x-edc-controlplane:8081
  dataplaneUrl: http://{{ .Release.Name }}-dataprovider-x-edc-dataplane:8081
  nameOverride: dataprovider-x
  secrets:
    edc-wallet-secret: changeme
  tractusx-connector:
    nameOverride: dataprovider-x-edc
    participant:
      id: BPNL00000003AYRE
    iatp:
      id: did:web:ssi-dim-wallet-stub.construct-x.net:BPNL00000003AYRE
      trustedIssuers:
        - did:web:ssi-dim-wallet-stub.construct-x.net:BPNL00000003CRHK
      sts:
        dim:
          url: https://ssi-dim-wallet-stub.construct-x.net/api/sts
        oauth:
          token_url: https://ssi-dim-wallet-stub.construct-x.net/oauth/token
          client:
            id: BPNL00000003AYRE
            secret_alias: edc-wallet-secret
    controlplane:
      env:
        TX_IAM_IATP_CREDENTIALSERVICE_URL: https://ssi-dim-wallet-stub.construct-x.net/api
        EDC_IAM_DID_WEB_USE_HTTPS: false
      bdrs:
        server:
          url: https://ssi-dim-wallet-stub.construct-x.net/api/v1/directory
      endpoints:
        management:
          authKey: TEST2
      ingresses:
        - enabled: true
          annotations: 
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hostname: "dataprovider-x-controlplane.construct-x.borrmann.dev"
          endpoints:
            - default
            - protocol
            - management
          className: "nginx"
          tls:
            enabled: true
      resources:
        limits:
          # -- Maximum CPU limit
          cpu: 1.5
          # -- Maximum memory limit
          memory: 1024Mi
        requests:
          # -- Initial CPU request
          cpu: 500m
          # -- Initial memory request
          memory: 1024Mi
    dataplane:
      env:
        TX_IAM_IATP_CREDENTIALSERVICE_URL: https://ssi-dim-wallet-stub.construct-x.net/api
        EDC_IAM_DID_WEB_USE_HTTPS: false
      ingresses:
        - enabled: true
          annotations: 
            nginx.ingress.kubernetes.io/ssl-redirect: "false"
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hostname: "dataprovider-x-dataplane.construct-x.borrmann.dev"
          endpoints:
            - default
            - public
          className: "nginx"
          tls:
            enabled: true
      token:
        signer:
          privatekey_alias: tokenSignerPrivateKey
        verifier:
          publickey_alias: tokenSignerPublicKey
      resources:
        limits:
          cpu: 1.5
          memory: 1024Mi
        requests:
          cpu: 500m
          memory: 1024Mi
  
    postgresql:
      nameOverride: dataprovider-x-db
      jdbcUrl: "jdbc:postgresql://{{ .Release.Name }}-dataprovider-x-db:5432/edc"
      auth:
        password: "dbpasswordtxdataprovider-x"
        postgresPassword: "dbpasswordtxdataprovider-x"
    vault:
      hashicorp:
        url: http://edc-dataprovider-x-vault:8200
      secretNames:
        transferProxyTokenSignerPrivateKey: tokenSignerPrivateKey
        transferProxyTokenSignerPublicKey: tokenSignerPublicKey
        transferProxyTokenEncryptionAesKey: tokenEncryptionAesKey

  vault:
    nameOverride: edc-dataprovider-x-vault
    fullnameOverride: edc-dataprovider-x-vault
    enabled: true
    server:
      postStart: []

  digital-twin-registry:
    nameOverride: dataprovider-x-dtr
    postgresql:
      nameOverride: dataprovider-x-dtr-db
      auth:
        password: "dbpassworddtrdataprovider-x"
        existingSecret: dataprovider-x-secret-dtr-postgres-init
    registry:
      ingress:
        enabled: true
        className: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$2
          nginx.ingress.kubernetes.io/x-forwarded-prefix: /semantics/registry
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: "dataprovider-x-dtr.construct-x.borrmann.dev"
            paths:
              - path: "/semantics/registry(/|$)(.*)"
                pathType: "Prefix"
            tls:
            - secretName: "dataprovider-x-dtr.tx.test-tls"
              hosts:
                - "dataprovider-x-dtr.construct-x.borrmann.dev"
      host: dataprovider-x-dtr.construct-x.borrmann.dev

  simple-data-backend:
    nameOverride: dataprovider-x-submodelserver
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        cert-manager.io/cluster-issuer: letsencrypt-prod
      className: "nginx"
      tls:
        - secretName: "submodelserver.tx.constructx-tls"
          hosts:
            - "dataprovider-x-submodelserver.construct-x.borrmann.dev"
      hosts:
        - host: "dataprovider-x-submodelserver.construct-x.borrmann.dev"
          paths:
            - path: "/"
              pathType: "Prefix"
      resources:
        limits:
          cpu: 500m
          memory: 1024Mi
        requests:
          cpu: 500m
          memory: 1024Mi

weather:
  enabled: false
