# Ingress Controller Configuration
ingress-nginx:
  controller:
    ingressClassResource:
      name: nginx
      enabled: true
      default: true
    service:
      type: LoadBalancer
    metrics:
      enabled: true

# Cert Manager Configuration  
cert-manager:
  installCRDs: true

# ClusterIssuer Configuration
clusterIssuer:
  name: letsencrypt-prod
  email: dennis@borrmann.dev