configuration:
  postgresuser: &postgresuser testuser
  postgrespass: &postgrespass testpass
  edcKey: &edcKey TEST

nameOverride: ""
fullnameOverride: ""
seedTestdata: false  # Toggle seeding of testdata. Can be enabled when the edc should be seeded with testdata on startup.
testdataConfigMap: ""  # Provide a custom configmap for post-install-job-upload-testdata.yaml.
backendUrl: ""  # Override the backend service url
registryUrl: ""  # Override the digital twin registry url
controlplanePublicUrl: ""  # Override the edc controlplane protocol url
controlplaneManagementUrl: ""  # Override the edc controlplane management url
dataplaneUrl: ""  # Override the edc dataplane public url
secrets:
  edc-wallet-secret: changeme

tractusx-connector:
  enabled: true
  install:
    postgresql: true
    vault: false
  participant:
    id: changeme
  iatp:
    id: changeme
    trustedIssuers:
      - changeme
    sts:
      dim:
        url: http://example.org
      oauth:
        token_url: http://example.org
        client:
          id: changeme
          secret_alias: client-secret
  controlplane:
    ingresses:
      - enabled: false
    bdrs:
      server:
        url: http://example.org
    endpoints:
      management:
        authKey: *edcKey
    securityContext:
      readOnlyRootFilesystem: false
    resources:
      limits:
          cpu: 1.5
          memory: 2048Mi
      requests:
        cpu: 500m
        memory: 1024Mi


  dataplane:
    ingresses:
      - enabled: false
    token:
      signer:
        privatekey_alias: changeme
      verifier:
        publickey_alias: changeme
    resources:
      limits:
        cpu: 1.5
        memory: 1024Mi
      requests:
        cpu: 500m
        memory: 500Mi

  vault:
    hashicorp:
      url: http://{{ .Release.Name }}-edc-provider-vault:8200
      token: "root"
    secretNames:
      transferProxyTokenSignerPrivateKey: changeme
      transferProxyTokenSignerPublicKey: changeme
      transferProxyTokenEncryptionAesKey: aesKey

  postgresql:
    nameOverride: edc-postgresql
    primary:
      persistence:
        enabled: false
        size: 1Gi
    auth:
      database: edc
      username: *postgresuser
      postgresPassword: *postgrespass
      password: *postgrespass
    username: *postgresuser
    password: *postgrespass
    jdbcUrl: "jdbc:postgresql://{{ .Release.Name }}-edc-postgresql:5432/edc"
    resources:
      limits:
          cpu: 500m
          memory: 500Mi
      requests:
        cpu: 250m
        memory: 256Mi

digital-twin-registry:
  enabled: true
  enableKeycloak: false

  postgresql:
    auth:
      existingSecret: registry-db-postresinit
    primary:
      persistence:
        enabled: false
        size: 1Gi
    resources:
      limits:
          cpu: 500m
          memory: 500Mi
      requests:
        cpu: 250m
        memory: 256Mi

  registry:
    host: digital-twin-registry.test
    ingress:
      enabled: false
    authentication: false
    livenessProbe:
      failureThreshold: 10
      initialDelaySeconds: 60
      periodSeconds: 10
    readinessProbe:
      failureThreshold: 10
      initialDelaySeconds: 60
      periodSeconds: 10

simple-data-backend:
  enabled: true
  image:
    tag: "main"
  ingress:
    enabled: false
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 1024Mi

vault:
  enabled: true
  nameOverride: edc-provider-vault
  injector:
    enabled: false
  server:
    postStart:
      - sh
      - -c
      - |-
        {
        sleep 5
        /bin/vault kv put secret/client-secret content=kEmH7QRPWhKfy8f+x0pFMw==
        /bin/vault kv put secret/aesKey content=YWVzX2VuY2tleV90ZXN0Cg==
        }
    dev:
      enabled: true
      devRootToken: root
    ingress:
      enabled: false